version: '3.9'

services:
  frontend:
    build: ./frontend/
    volumes:
      - static:/mnt/static/:rw
      - shared:/app/src/shared/:ro
    depends_on:
      - shared
  backend:
    build: ./backend/
    init: true # allows to exit gracefully
    volumes:
      - data:/mnt/data/:rw
      - shared:/app/src/shared/:ro
    environment:
      - ENTRYPOINT=https://zst-radom.edu.pl/nauczyciele/
    depends_on:
      - shared
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - static:/mnt/static/:ro
      - data:/mnt/data/:ro
  shared:
    build: ./shared/
    volumes:
      - shared:/mnt/shared/:rw

volumes:
  static:
  data:
  shared:
