version: '3.9'

services:
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    volumes:
      - static:/mnt/static/:rw
  backend:
    build: 
      context: ./
      dockerfile: backend.Dockerfile
    init: true # allows to exit gracefully
    volumes:
      - data:/mnt/data/:rw
    environment:
      - ENTRYPOINT=https://zst-radom.edu.pl/nauczyciele/
  nginx:
    build: 
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - static:/mnt/static/:ro
      - data:/mnt/data/:ro

volumes:
  static:
  data:
